baseURL = 'https://sarahkurek.github.io/'
#languageCode = 'en-us'
title = 'Emotions in Drama'
author = 'Sarah Kurek'
theme = 'bootstrap-bp-hugo-theme'

[Author]  
  name = "Sarah Kurek"

[params]
    alwaysExpandMenu = true
    hideReadingTime = true

[languages]
    [languages.en]
        languageName = "English"
        contentDir = "content/english"
        title = "Emotions in Drama"
        weight = 1
        
        [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
        pre = "<i class='fas fa-clipboard'></i>"
    
            
        [[languages.en.menu.main]]
            identifier = "team"
            name = "Team"
            url = "/team/"
            weight = 20
            pre = "<i class='fas fa-address-card'></i>"
            
        [[languages.en.menu.main]]
            identifier = "publications"
            name = "Publications"
            url = "/publications/"
            weight = 30
            pre = "<i class='fas fa-file'></i>"


        [[languages.en.menu.footer]]
            identifier = "Imprint"
            name = "Imprint"
            url = "/imprint/"
            weight = 10

    [languages.de]
        languageName = "Deutsch"
        contentDir = "content/german"
        title = "Emotionen in Dramen"
        weight = 2
        
        [languages.de.menu]
        [[languages.de.menu.main]]
            identifier = "info"
            name = "Info"
            url = "/de/info/"
            weight = 10
            
        [[languages.de.menu.main]]
            identifier = "autoren"
            name = "Autoren"
            url = "/de/autoren/"
            weight = 20

        [[languages.de.menu.main]]
            identifier = "publikationen"
            name = "Publikationen"
            url = "/de/publikationen/"
            weight = 30
            
        [[languages.de.menu.footer]]
            identifier = "impressum"
            name = "Impressum"
            url = "/de/impressum/"
            weight = 10
